<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Пакеты услуг");
?>

<?/*
<div class="sort">
	<p>Сортировка:</p>
	<ul>
		<li><span>Стоимость</span></li>
		<li><a href="#">Название</a></li>
	</ul>
</div><!--sort-->
*/?>
<? 
if ($USER->GetLogin() == "vadim")
{

	$GLOBALS["arrFilter"]["PROPERTY_ONLY_REG"] =false;
	$GLOBALS["arrFilter"][">PROPERTY_price"] = 0;
	?>
	<?$APPLICATION->IncludeComponent(
	    "bitrix:catalog.section",
	    "pay_packets",
	    Array(
	        "ACTION_VARIABLE" => "action",
	        "ADD_PICT_PROP" => "MORE_PHOTO",
	        "ADD_PROPERTIES_TO_BASKET" => "Y",
	        "ADD_SECTIONS_CHAIN" => "N",
	        "ADD_TO_BASKET_ACTION" => "ADD",
	        "BASKET_URL" => "/personal/basket.php",
	        "BROWSER_TITLE" => "-",
	        "CACHE_FILTER" => "N",
	        "CACHE_GROUPS" => "Y",
	        "CACHE_TIME" => "36000000",
	        "CACHE_TYPE" => "A",
	        "CONVERT_CURRENCY" => "Y",
	        "CURRENCY_ID" => "RUB",
	        "CUSTOM_FILTER" => "",
	        "DETAIL_URL" => "",
	        "DISPLAY_BOTTOM_PAGER" => "Y",
	        "DISPLAY_TOP_PAGER" => "N",
	        "ELEMENT_SORT_FIELD" => "sort",
	        "ELEMENT_SORT_FIELD2" => "NAME",
	        "ELEMENT_SORT_ORDER" => "asc",
	        "ELEMENT_SORT_ORDER2" => "ASC",
	        "ENLARGE_PRODUCT" => "PROP",
	        "ENLARGE_PROP" => "NEWPRODUCT",
	        "FILTER_NAME" => "arrFilter",
	        "IBLOCK_ID" => "6",
	        "IBLOCK_TYPE" => "money",
	        "INCLUDE_SUBSECTIONS" => "Y",
	        "LINE_ELEMENT_COUNT" => "3",
	        "LOAD_ON_SCROLL" => "N",
	        "MESSAGE_404" => "",
	        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
	        "MESS_BTN_BUY" => "Купить",
	        "MESS_BTN_DETAIL" => "Подробнее",
	        "MESS_BTN_LAZY_LOAD" => "Показать ещё",
	        "MESS_BTN_SUBSCRIBE" => "Подписаться",
	        "MESS_NOT_AVAILABLE" => "Нет в наличии",
	        "META_DESCRIPTION" => "-",
	        "META_KEYWORDS" => "-",
	        "OFFERS_FIELD_CODE" => array("",""),
	        "OFFERS_LIMIT" => "5",
	        "OFFERS_SORT_FIELD" => "sort",
	        "OFFERS_SORT_FIELD2" => "id",
	        "OFFERS_SORT_ORDER" => "asc",
	        "OFFERS_SORT_ORDER2" => "desc",
	        "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
	        "PAGER_BASE_LINK_ENABLE" => "N",
	        "PAGER_DESC_NUMBERING" => "N",
	        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	        "PAGER_SHOW_ALL" => "N",
	        "PAGER_SHOW_ALWAYS" => "N",
	        "PAGER_TEMPLATE" => ".default",
	        "PAGER_TITLE" => "Товары",
	        "PAGE_ELEMENT_COUNT" => "20",
	        "PARTIAL_PRODUCT_PROPERTIES" => "N",
	        "PRICE_CODE" => array("base"),
	        "PRICE_VAT_INCLUDE" => "Y",
	        "PRODUCT_SUBSCRIPTION" => "Y",
	        "PROPERTY_CODE" => array("*"),
	        "PROPERTY_CODE_MOBILE" => array(),
	        "RCM_TYPE" => "personal",
	        "SECTION_CODE" => "",
	        "SECTION_ID" => "",
	        "SECTION_ID_VARIABLE" => "",
	        "SECTION_URL" => "",
	        "SECTION_USER_FIELDS" => array("",""),
	        "SEF_MODE" => "N",
	        "SET_BROWSER_TITLE" => "Y",
	        "SET_LAST_MODIFIED" => "N",
	        "SET_META_DESCRIPTION" => "Y",
	        "SET_META_KEYWORDS" => "Y",
	        "SET_STATUS_404" => "N",
	        "SET_TITLE" => "Y",
	        "SHOW_404" => "N",
	        "SHOW_ALL_WO_SECTION" => "N",
	        "SHOW_CLOSE_POPUP" => "N",
	        "SHOW_DISCOUNT_PERCENT" => "Y",
	        "SHOW_FROM_SECTION" => "N",
	        "SHOW_MAX_QUANTITY" => "N",
	        "SHOW_OLD_PRICE" => "N",
	        "SHOW_PRICE_COUNT" => "1",
	        "SHOW_SLIDER" => "Y",
	        "SLIDER_INTERVAL" => "3000",
	        "SLIDER_PROGRESS" => "N",
	        "TEMPLATE_THEME" => "blue",
	        "USE_ENHANCED_ECOMMERCE" => "Y",
	        "USE_MAIN_ELEMENT_SECTION" => "N",
	        "USE_PRICE_COUNT" => "N",
	        "USE_PRODUCT_QUANTITY" => "N"
	    )
	);
}
?>
<?/*$APPLICATION->IncludeComponent(
    "bitrix:catalog.section",
    "pay_objects",
    Array(
        "ACTION_VARIABLE" => "action",
        "ADD_PICT_PROP" => "MORE_PHOTO",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => "N",
        "ADD_TO_BASKET_ACTION" => "ADD",
        "BASKET_URL" => "/personal/basket.php",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CONVERT_CURRENCY" => "Y",
        "CURRENCY_ID" => "RUB",
        "CUSTOM_FILTER" => "",
        "DETAIL_URL" => "",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "ELEMENT_SORT_FIELD" => "sort",
        "ELEMENT_SORT_FIELD2" => "NAME",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_ORDER2" => "ASC",
        "ENLARGE_PRODUCT" => "PROP",
        "ENLARGE_PROP" => "NEWPRODUCT",
        "FILTER_NAME" => "arrFilter",
        "IBLOCK_ID" => "27",
        "IBLOCK_TYPE" => "money",
        "INCLUDE_SUBSECTIONS" => "Y",
        "LINE_ELEMENT_COUNT" => "3",
        "LOAD_ON_SCROLL" => "N",
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_BTN_LAZY_LOAD" => "Показать ещё",
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "OFFERS_FIELD_CODE" => array("",""),
        "OFFERS_LIMIT" => "5",
        "OFFERS_SORT_FIELD" => "sort",
        "OFFERS_SORT_FIELD2" => "id",
        "OFFERS_SORT_ORDER" => "asc",
        "OFFERS_SORT_ORDER2" => "desc",
        "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => ".default",
        "PAGER_TITLE" => "Товары",
        "PAGE_ELEMENT_COUNT" => "8",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array("base"),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRODUCT_SUBSCRIPTION" => "Y",
        "PROPERTY_CODE" => array("*"),
        "PROPERTY_CODE_MOBILE" => array(),
        "RCM_TYPE" => "personal",
        "SECTION_CODE" => "",
        "SECTION_ID" => "",
        "SECTION_ID_VARIABLE" => "",
        "SECTION_URL" => "",
        "SECTION_USER_FIELDS" => array("",""),
        "SEF_MODE" => "N",
        "SET_BROWSER_TITLE" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "Y",
        "SHOW_404" => "N",
        "SHOW_ALL_WO_SECTION" => "N",
        "SHOW_CLOSE_POPUP" => "N",
        "SHOW_DISCOUNT_PERCENT" => "Y",
        "SHOW_FROM_SECTION" => "N",
        "SHOW_MAX_QUANTITY" => "N",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_SLIDER" => "Y",
        "SLIDER_INTERVAL" => "3000",
        "SLIDER_PROGRESS" => "N",
        "TEMPLATE_THEME" => "blue",
        "USE_ENHANCED_ECOMMERCE" => "Y",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "N"
    )
);*/?>

<?/*$APPLICATION->IncludeComponent('wexpert:iblock.list', 'pay_packets', array(
	'IBLOCK_ID'     => 6,
	'PAGESIZE'      => 8,
	'ORDER'         => array('SORT' => 'ASC', 'NAME' => 'ASC'),
	'SELECT'        => array(),
	'GET_PROPERTY'  => 'Y',
	'CACHE_TIME'    => 0,
	'SET_404'       => 'N'
));*/?>



<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>